/**
 * Public site routes for sitemap.xml and internal route inventory.
 * Admin / astro-ops / API paths are excluded from the sitemap.
 */

export type SiteRouteEntry = {
  path: string;
  changeFrequency: "daily" | "weekly" | "monthly";
  priority: number;
  note?: string;
};

/** Included in /sitemap.xml */
export const PUBLIC_SITEMAP_ROUTES: SiteRouteEntry[] = [
  { path: "", changeFrequency: "daily", priority: 1 },
  { path: "/free-kundli", changeFrequency: "weekly", priority: 0.9 },
  { path: "/free-kundli/result", changeFrequency: "weekly", priority: 0.7 },
  { path: "/free-kundli/result/b", changeFrequency: "weekly", priority: 0.6 },
  { path: "/astro-path/free-kundli", changeFrequency: "weekly", priority: 0.85 },
  { path: "/astro-path/free-kundli/result", changeFrequency: "weekly", priority: 0.7 },
  { path: "/checkout/kundli", changeFrequency: "weekly", priority: 0.85 },
  { path: "/checkout/consultation", changeFrequency: "weekly", priority: 0.85 },
  { path: "/astro-path/checkout/kundli", changeFrequency: "weekly", priority: 0.8 },
  { path: "/consultation", changeFrequency: "weekly", priority: 0.9 },
  { path: "/kundli-report", changeFrequency: "weekly", priority: 0.85 },
  { path: "/premium-kundli-review", changeFrequency: "weekly", priority: 0.75 },
  { path: "/tools", changeFrequency: "weekly", priority: 0.8 },
  { path: "/tools/kundal-dhatu", changeFrequency: "weekly", priority: 0.75 },
  { path: "/tools/muhurat", changeFrequency: "weekly", priority: 0.75 },
  { path: "/tools/numerology", changeFrequency: "weekly", priority: 0.75 },
  { path: "/tools/name-letter/a", changeFrequency: "weekly", priority: 0.7 },
  {
    path: "/tools/name-letter/a/free-kundli",
    changeFrequency: "weekly",
    priority: 0.65,
  },
  { path: "/astro-path/tools/kundal-dhatu", changeFrequency: "weekly", priority: 0.7 },
  { path: "/ads/tools/kundal-dhatu", changeFrequency: "weekly", priority: 0.7 },
  { path: "/ads/free-kundli", changeFrequency: "weekly", priority: 0.85 },
  { path: "/ads/free-kundli/result", changeFrequency: "weekly", priority: 0.7 },
  { path: "/ads/checkout/kundli", changeFrequency: "weekly", priority: 0.8 },
  { path: "/about", changeFrequency: "monthly", priority: 0.6 },
  { path: "/faq", changeFrequency: "monthly", priority: 0.6 },
  { path: "/support", changeFrequency: "monthly", priority: 0.55 },
  { path: "/login", changeFrequency: "monthly", priority: 0.4 },
  { path: "/signup", changeFrequency: "monthly", priority: 0.4 },
  { path: "/astrologers", changeFrequency: "daily", priority: 0.85 },
  { path: "/free-services", changeFrequency: "monthly", priority: 0.5 },
  { path: "/pooja", changeFrequency: "monthly", priority: 0.45 },
  { path: "/remedy", changeFrequency: "monthly", priority: 0.45 },
  { path: "/gift-card", changeFrequency: "monthly", priority: 0.45 },
  { path: "/following", changeFrequency: "monthly", priority: 0.4 },
  { path: "/assistant", changeFrequency: "monthly", priority: 0.4 },
];

/** Full inventory for docs — not all are in sitemap.xml */
export const SITE_ROUTE_INVENTORY = {
  public: PUBLIC_SITEMAP_ROUTES,
  auth: [
    { path: "/auth/callback", note: "OAuth / magic link callback" },
    { path: "/user", note: "Account home (login required)" },
    { path: "/users/settings", note: "User settings (login required)" },
    { path: "/profile", note: "Profile" },
    { path: "/orders", note: "Order history" },
  ],
  thankYou: ["/thank-you/kundli", "/thank-you/consultation"],
  astrologers: [
    "/astrologers",
    "/astrologers/[slug]",
    "/astrologers/chats",
    "/astrologers/chats/[sessionId]",
    "/astrologers/chats/waiting/[sessionId]",
    "/astrologers/wallet",
  ],
  admin: [
    "Configured via NEXT_PUBLIC_ADMIN_PANEL_PATH (default vg-console-8f3k2p)",
    "/[admin]/login",
    "/[admin]",
    "/[admin]/orders",
    "/[admin]/orders/[id]",
    "/[admin]/leads",
    "/[admin]/leads/[id]",
    "/[admin]/payments",
    "/[admin]/products",
    "/[admin]/coupons",
    "/[admin]/consultations",
    "/[admin]/reviews",
    "/[admin]/support",
    "/[admin]/integrations",
    "/[admin]/automations",
    "/[admin]/settings",
    "/[admin]/analytics",
    "/[admin]/analytics/funnels",
    "/[admin]/analytics/funnels/kfp",
    "/[admin]/content",
    "/[admin]/content/pages",
    "/[admin]/content/faqs",
    "/[admin]/content/testimonials",
    "/[admin]/content/banners",
    "/[admin]/post-upsell",
    "/[admin]/team",
    "/[admin]/tools",
    "/[admin]/logs",
  ],
  astroOps: [
    "Configured via NEXT_PUBLIC_ASTRO_OPS_PATH (default vg-astral-9m4q1x)",
    "/[astro-ops]",
    "/[astro-ops]/inbox",
    "/[astro-ops]/sessions",
    "/[astro-ops]/sessions/[sessionId]",
    "/[astro-ops]/users",
    "/[astro-ops]/users/[userId]",
    "/[astro-ops]/astrologers",
    "/[astro-ops]/wallet-ledger",
    "/[astro-ops]/settings",
  ],
  api: [
    "POST /api/payments/create-order",
    "POST /api/payments/create-consultation-order",
    "POST /api/payments/verify",
    "POST /api/payments/failure",
    "POST /api/coupons/validate",
    "POST /api/checkout/view",
    "POST /api/kundli/submit",
    "POST /api/leads/capture",
    "POST /api/events/track",
    "POST /api/support",
    "POST /api/reviews/premium-kundli",
    "POST /api/auth/phone-otp/send",
    "POST /api/auth/phone-otp/verify",
    "GET|POST /api/user/chat-sessions",
    "POST /api/user/chat-sessions/[sessionId]/close",
    "POST /api/user/chat-sessions/[sessionId]/meter",
    "POST /api/user/wallet/create-recharge-order",
    "POST /api/user/wallet/verify-recharge",
    "GET /api/user/wallet/topup-info",
    "POST /api/admin/orders/[orderId]/kundli-report-upload",
    "POST /api/admin/live-consult/chat",
    "POST /api/admin/live-consult/session/start",
    "POST /api/cron/scheduled-kundli-deliveries",
  ],
  system: ["/robots.txt", "/sitemap.xml"],
} as const;
